### ISSUE TITLE
Attempt to make a Lovelace UI version of my HA Dashboard

### ISSUE THREAD

**Issue by corbanmailloux** [corbanmailloux/home-assistant-configuration#37]
Mostly just for fun. If it's very nice, I'll consider switching the wall display view to Lovelace.

**Comment by corbanmailloux** [comment]
For reference, this is my current HA Dashboard (I should add this to the README):
![image](https://user-images.githubusercontent.com/2474463/55284404-faf84680-5343-11e9-9c8c-c80ab4af201f.png)

**Comment by corbanmailloux** [comment]
The current tablet I'm using for the wall display doesn't seem to support the Lovelace UI. I'm considering revamping my wall display set up soon.

**Comment by callagga** [comment]
How did you go? Able to summarise the pros/cons of trying to use Lovelace instead of hadashboard for a dashboard?

**Comment by corbanmailloux** [comment]
At this point, I think Lovelace is incredibly powerful. If I were building a new wall display today, I would start with Lovelace.

The outdated tablet I'm currently using can't run Lovelace, so I am still running an HA dashboard on it. This is a project that I plan to come back to in a few more months.

**Comment by corbanmailloux** [comment]
I've moved to a new apartment and now it's time to rebuild the wall display. I found my old [Samsung Galaxy Note 10.1 tablet](https://en.wikipedia.org/wiki/Samsung_Galaxy_Note_10.1) and have started building a totally new display, built in Lovelace. It uses the [Fully Kiosk browser](https://www.fully-kiosk.com/) to allow extra control of the tablet from within Home Assistant.

I plan to use [conditional cards](https://www.home-assistant.io/lovelace/conditional/) to have the interface only display information that's relevant given other conditions. Here's the first example I've built so far: When my partner is on her way home from work, add a map card to the UI to show me where she is and her ETA. Once she arrives home, hide the cards so they don't take up space in the dashboard.

Once I have a few more situations covered, I'll need to do some UI arrangement to make the display look nice and then I'll give a comparison between Lovelace and HADashboard. 

I'll link the work I'm doing for the new display to this issue for traceability.

**Comment by corbanmailloux** [comment]
Another idea for the conditional cards:
- Re-add the Octoprint integration.
- When a 3D print is running, add a card on the display for progress with an emergency stop button (`switch.turn_off` on the smart switch it's connected to).

**Comment by corbanmailloux** [comment]
It's a continuous work in progress (as is all home automation, right?), but I have a wall display dashboard system I'm happy with.
Here's an example normal screenshot: 
![image](https://user-images.githubusercontent.com/2474463/103472041-51cf5300-4d56-11eb-87a2-f57b4e81b068.png)

Something I think is unique to my setup is the right side column: "Dynamic Cards"
This is a column of conditional cards that functions as a sort of whole-home notification bar, showing cards with additional data when it's relevant. 
Some examples:
![image](https://user-images.githubusercontent.com/2474463/103472048-8cd18680-4d56-11eb-9337-199d92d187ec.png)
- We have cats, and the litter box needs to be cleaned daily. If we haven't cleaned the box by 7PM, a notification is displayed (and pushed to our phones). If tapped, the box is marked as cleaned and the notification is dismissed on our phones.
- I work from home but my fiancé goes into the office. When she's heading home from work, a map is displayed along with her ETA, allowing me to start dinner or otherwise prep for her arrival.
- We have a specific schedule for our trash pickup service, so display a card during the times we can put out the trash.
- When I'm on a call for work, display a card indicating such. The wall display is mounted immediately outside my office, so this is a visible indicator not to walk into the room. If my webcam is active, the card also displays that information.
- We use a package locker system. If there are packages waiting to be picked up, show a card.

This system continues to evolve, but I've been really liking the dynamic nature of this setup. Any time there's a new, regularly-occurring, whole-home kind of detail to share, I can just add a new dynamic/conditional card. The rest of the wall display is static (but interactive) cards.

I'm closing this issue now. I'll copy some of this information to the main README in the repo to explain the parts of the dashboard.
