### ISSUE TITLE
Sensor for Showing the Coordinator Version not showing the desired data

### ISSUE THREAD

**Issue by sesarhayo** [corbanmailloux/home-assistant-configuration#50]
At present, not showing the desired data: the date of the revision
`# Sensor for Showing the Coordinator Version
  - platform: mqtt
    name: Coordinator Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator }}"
    icon: mdi:chip`

I suggest changing it to
`# Sensor for Showing the Coordinator Version
  - platform: mqtt
    name: Coordinator Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator.meta.revision }}"
    icon: mdi:chip`

Thanks.

**Comment by corbanmailloux** [comment]
Thanks! I took this block from the [zigbee2mqtt docs](https://www.zigbee2mqtt.io/integration/home_assistant.html#controlling-zigbee2mqtt-via-home-assistant), but I like your suggestion.
