### ISSUE TITLE
Move to the new Google Domains component for dynamic DNS

### ISSUE THREAD

**Issue by corbanmailloux** [corbanmailloux/home-assistant-configuration#9]
https://home-assistant.io/components/google_domains/

Moving as much functionality into my HASS configuration makes a full reinstall significantly easier.

**Comment by corbanmailloux** [comment]
Something doesn't seem to be working right here, so I'm switching back for now.

**Comment by corbanmailloux** [comment]
Looks like the component tried to set an `AAAA` record (IPv6) instead of an `A` (IPv4). Interesting.

**Comment by corbanmailloux** [comment]
On hass.io, I'm back on DuckDNS for now. I don't love this answer, but I needed to get it up and working first.

**Comment by Smitty357** [comment]
Have you found a way to force IPv4 yet? Mine is doing the same, generating the IPv6. The problem with it is it is not my IP, but my providers hub that is being found. I can manually change it, and disable the info in my config file to prevent it from going back, hopefully it does not change.

**Comment by corbanmailloux** [comment]
I didn't find a way to force IPv4. I used to use `ddclient` ([which now has Google Domains support](https://support.google.com/domains/answer/6147083?hl=en)) before I moved to HassIO. If you have a standard Home Assistant installation running on a "normal" Linux machine, that may be another option for you.

I'm still running right now with DuckDNS and a CNAME record. I'm not too happy with the reliance on another service, but it's been stable and I haven't had the time to look into it again.

---

I just took a minute to look into it. If you'd like to open an issue/feature request for HASS, here's some helpful information:

In the "Using the API to update your Dynamic DNS record" section of the [help docs for the Google Domains API](https://support.google.com/domains/answer/6147083?hl=en), it says in regards to the `myip` parameter:
>The IP address to which the host will be set. If not supplied, we’ll use the IP of the agent that sent the request.
>Note: Because the address must be an IPv4 address, `myip` is required if your agent uses an IPv6 address. You can check your agent’s IP address by going to https://domains.google.com/checkip.

Looking at the [HASS source for the Google Domains component](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/google_domains.py#L78), it just makes a simple call to the API and doesn't provide this parameter. 
For comparison, the CloudFlare component uses a service called https://www.ipify.org/ to get the IP address to update, but that all happens inside an [external library](https://gitlab.com/ludeeus/pycfdns/blob/master/pycfdns/__init__.py#L12).


From what I see at the moment, here how someone could fix the Google Domains component:
* Create a new Python library to encapsulate the Google Domains logic. This is due to a [Home Assistant development rule](https://developers.home-assistant.io/docs/en/creating_platform_index.html): 
  >[...] platform logic should never interface directly with devices. Instead, use a third-party Python 3 library. This way, Home Assistant can share code with the Python community and keep the project maintainable.
  * In this library, call out to a service like https://www.ipify.org/ to get the right IP address, and publish the message to the Google Domains API.
* Update the existing [Google Domains component](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/google_domains.py) to use this library instead of a direct API call.


This is definitely doable and should be relatively straightforward, I just don't have to time these days to work on it right now. I'll keep this issue open for me to remember in the future.

If you're comfortable with it, I'd suggest posting in the [feature requests](https://community.home-assistant.io/c/feature-requests) or [third-party integrations](https://community.home-assistant.io/c/third-party) sections of the Home Assistant forums for additional help. You are welcome to reference this comment or copy its content if it helps.

**Comment by FutureTense** [comment]
I find it’s just easier to create a script and call the curl command

**Comment by air720boarder** [comment]
Any progress on this?

**Comment by corbanmailloux** [comment]
@air720boarder No, I never went back to this. I use the [DuckDNS Hass.io addon](https://www.home-assistant.io/addons/duckdns/) and just have a CNAME record from my actual domain name to the DuckDNS name. 

It's been very stable so far. I don't love depending on another service (DuckDNS), but it's good enough for me at this point. If you're having similar issues and would like to report it to HASS, the information above could be useful. You can also link to this issue for context.

For now, I'm closing this issue.
